[package]
name = "mush"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>"]
license = "Apache-2.0"
keywords = ["visual","gui","graph"]
repository = "https://github.com/PistonDevelopers/mush"

[dependencies]